version: '3.8'

services:
  android-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ionic-android-builder:latest
    container_name: ionic-android-builder
    volumes:
      - .:/app
      - gradle_cache:/root/.gradle
      - android_sdk_cache:/opt/android-sdk
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk

volumes:
  gradle_cache:
  android_sdk_cache:
